Add key constraints for the JoinOrder benchmark
hyrise/hyrise pull request #2372
Opened 2021-06-09 20:34 UTC by julianmenzler

Currently, we do not really profit from key constraints in the JOB benchmark. But, this may change in the future.

<details>
<summary>Configuration Overview - click to expand</summary>

```diff
 +Configuration Overview---------------------------------------------+------------------------------------------------+
 | Parameter        | job_master_80e13c.json                         | job_add_constraints_9993c36.json               |
 +------------------+------------------------------------------------+------------------------------------------------+
 |  GIT-HASH        | 80e13c23d433b8b0c4b562084def804b2c94d415-dirty | 9993c36501916fe9da6efbc986cea93b733ae265-dirty |
 |  benchmark_mode  | Ordered                                        | Ordered                                        |
 |  build_type      | release                                        | release                                        |
 |  chunk_size      | 65535                                          | 65535                                          |
 |  clients         | 1                                              | 1                                              |
 |  compiler        | gcc 9.2                                        | gcc 9.2                                        |
 |  cores           | 0                                              | 0                                              |
 |  date            | 2021-06-09 13:21:04                            | 2021-06-09 15:20:52                            |
 |  encoding        | {'default': {'encoding': 'Dictionary'}}        | {'default': {'encoding': 'Dictionary'}}        |
 |  indexes         | False                                          | False                                          |
 |  max_duration    | 60000000000                                    | 60000000000                                    |
 |  max_runs        | -1                                             | -1                                             |
 |  time_unit       | ns                                             | ns                                             |
 |  using_scheduler | False                                          | False                                          |
 |  verify          | False                                          | False                                          |
 |  warmup_duration | 0                                              | 0                                              |
 +------------------+------------------------------------------------+------------------------------------------------+
```
</details>

```diff
 +---------++----------+----------+--------++----------+----------+--------+---------+
 | Item    || Latency (ms/iter)   | Change || Throughput (iter/s) | Change | p-value |
 |         ||      old |      new |        ||      old |      new |        |         |
 +---------++----------+----------+--------++----------+----------+--------+---------+
 | 10a     ||    737.7 |    737.5 |   -0%  ||     1.36 |     1.36 |   +0%  |  0.9757 |
 | 10b     ||    715.6 |    706.9 |   -1%  ||     1.40 |     1.41 |   +1%  |  0.0000 |
+| 10c     ||   1651.4 |   1380.2 |  -16%  ||     0.61 |     0.72 |  +20%  |  0.0000 |
 | 11a     ||    269.9 |    262.3 |   -3%  ||     3.70 |     3.81 |   +3%  |  0.0802 |
 | 11b     ||    255.9 |    254.8 |   -0%  ||     3.91 |     3.92 |   +0%  |  0.7944 |
+| 11c     ||    999.1 |    924.6 |   -7%  ||     1.00 |     1.08 |   +8%  |  0.0000 |
+| 11d     ||  10667.9 |   9828.6 |   -8%  ||     0.09 |     0.10 |   +9%  |       ˅ |
+| 12a     ||    587.2 |    554.9 |   -6%  ||     1.70 |     1.80 |   +6%  |  0.0010 |
 | 12b     ||    354.3 |    355.8 |   +0%  ||     2.82 |     2.81 |   -0%  |  0.8059 |
 | 12c     ||   6688.3 |   6685.6 |   -0%  ||     0.15 |     0.15 |   +0%  |       ˅ |
-| 13a     ||    332.8 |    455.8 |  +37%  ||     3.00 |     2.19 |  -27%  |  0.0000 |
 | 13b     ||    424.0 |    406.7 |   -4%  ||     2.36 |     2.46 |   +4%  |  0.0000 |
+| 13c     ||    320.6 |    304.4 |   -5%  ||     3.12 |     3.29 |   +5%  |  0.0000 |
-| 13d     ||    332.5 |    454.5 |  +37%  ||     3.01 |     2.20 |  -27%  |  0.0000 |
 | 14a     ||   8012.3 |   8010.0 |   -0%  ||     0.12 |     0.12 |   +0%  |       ˅ |
 | 14b     ||   8360.9 |   8347.9 |   -0%  ||     0.12 |     0.12 |   +0%  |       ˅ |
 | 14c     ||   8018.9 |   7998.2 |   -0%  ||     0.12 |     0.13 |   +0%  |       ˅ |
 | 15a     ||    406.5 |    397.0 |   -2%  ||     2.46 |     2.52 |   +2%  |  0.0071 |
 | 15b     ||    394.5 |    388.7 |   -1%  ||     2.53 |     2.57 |   +2%  |  0.0142 |
 | 15c     ||    304.0 |    305.5 |   +1%  ||     3.29 |     3.27 |   -1%  |  0.6084 |
+| 15d     ||    925.6 |    755.5 |  -18%  ||     1.08 |     1.32 |  +23%  |  0.0000 |
+| 16a     ||  10151.2 |   9528.8 |   -6%  ||     0.10 |     0.10 |   +7%  |       ˅ |
 | 16b     ||  13112.9 |  12615.7 |   -4%  ||     0.08 |     0.08 |   +4%  |       ˅ |
+| 16c     ||  10406.0 |   9890.9 |   -5%  ||     0.10 |     0.10 |   +5%  |       ˅ |
+| 16d     ||  10326.5 |   9758.4 |   -6%  ||     0.10 |     0.10 |   +6%  |       ˅ |
 | 17a     ||   1879.9 |   1837.0 |   -2%  ||     0.53 |     0.54 |   +2%  |  0.0294 |
 | 17b     ||   1537.3 |   1512.1 |   -2%  ||     0.65 |     0.66 |   +2%  |  0.0884 |
 | 17c     ||   1460.7 |   1430.9 |   -2%  ||     0.68 |     0.70 |   +2%  |  0.0475 |
 | 17d     ||   1662.6 |   1637.8 |   -1%  ||     0.60 |     0.61 |   +2%  |  0.1354 |
+| 17e     ||   5371.3 |   5071.9 |   -6%  ||     0.19 |     0.20 |   +6%  |  0.0000 |
 | 17f     ||   2991.8 |   2897.7 |   -3%  ||     0.33 |     0.35 |   +3%  |  0.0092 |
-| 18a     ||   1180.6 |   1694.2 |  +44%  ||     0.85 |     0.59 |  -30%  |  0.0000 |
 | 18b     ||    529.0 |    523.2 |   -1%  ||     1.89 |     1.91 |   +1%  |  0.2280 |
 | 18c     ||   7017.4 |   7048.7 |   +0%  ||     0.14 |     0.14 |   -0%  |       ˅ |
 | 19a     ||  10565.6 |  10474.0 |   -1%  ||     0.09 |     0.10 |   +1%  |       ˅ |
 | 19b     ||   4963.7 |   4892.0 |   -1%  ||     0.20 |     0.20 |   +1%  |  0.0136 |
 | 19c     ||  10224.0 |  10208.5 |   -0%  ||     0.10 |     0.10 |   +0%  |       ˅ |
+| 19d     ||  10832.3 |   9573.1 |  -12%  ||     0.09 |     0.10 |  +13%  |       ˅ |
 | 1a      ||    114.9 |    113.9 |   -1%  ||     8.70 |     8.78 |   +1%  |  0.0000 |
 | 1b      ||     47.4 |     47.7 |   +0%  ||    21.07 |    20.98 |   -0%  |  0.0000 |
 | 1c      ||     48.2 |     48.2 |   +0%  ||    20.76 |    20.74 |   -0%  |  0.1054 |
 | 1d      ||     47.4 |     47.6 |   +0%  ||    21.09 |    20.99 |   -0%  |  0.0000 |
 | 20a     ||   2209.3 |   2174.5 |   -2%  ||     0.45 |     0.46 |   +2%  |  0.0001 |
 | 20b     ||   1894.0 |   1859.5 |   -2%  ||     0.53 |     0.54 |   +2%  |  0.0000 |
 | 20c     ||   1231.6 |   1203.4 |   -2%  ||     0.81 |     0.83 |   +2%  |  0.0000 |
 | 21a     ||   7406.4 |   7455.2 |   +1%  ||     0.14 |     0.13 |   -1%  |       ˅ |
 | 21b     ||    411.2 |    423.6 |   +3%  ||     2.43 |     2.36 |   -3%  |  0.0000 |
 | 21c     ||   7704.5 |   7772.1 |   +1%  ||     0.13 |     0.13 |   -1%  |       ˅ |
 | 22a     ||   6378.4 |   6340.0 |   -1%  ||     0.16 |     0.16 |   +1%  |  0.6619 |
 | 22b     ||   6369.2 |   6341.0 |   -0%  ||     0.16 |     0.16 |   +0%  |  0.7545 |
 | 22c     ||   8035.7 |   8025.7 |   -0%  ||     0.12 |     0.12 |   +0%  |       ˅ |
 | 22d     ||   8071.1 |   8044.6 |   -0%  ||     0.12 |     0.12 |   +0%  |       ˅ |
 | 23a     ||    303.9 |    296.2 |   -3%  ||     3.29 |     3.38 |   +3%  |  0.0003 |
 | 23b     ||    221.6 |    218.9 |   -1%  ||     4.51 |     4.57 |   +1%  |  0.0594 |
 | 23c     ||    323.0 |    316.5 |   -2%  ||     3.10 |     3.16 |   +2%  |  0.0035 |
 | 24a     ||   5238.1 |   5031.9 |   -4%  ||     0.19 |     0.20 |   +4%  |  0.0098 |
 | 24b     ||   5086.2 |   4954.5 |   -3%  ||     0.20 |     0.20 |   +3%  |  0.3086 |
 | 25a     ||    533.5 |    530.7 |   -1%  ||     1.87 |     1.88 |   +1%   [...]

2021-06-10 16:50 UTC, Bensk1 requested changes

2021-06-10 16:51 UTC, Bensk1 commented
Some queries lose performance. Is this due to the fact that the constraints enable JoinToSemiJoinRewrites (ColumnPruningRule) and these SemiJoins prevent some SemiJoinReductions?

2021-06-10 16:59 UTC, julianmenzler commented on src/benchmark/join_order_benchmark.cpp
> + * Each of the 20 JOB tables has one surrogate key. This function registers key constraints for all of them.
You are right, `name` is missing. Thanks for catching this!

2021-06-10 17:05 UTC, Bensk1 commented
Probably I was the one missing the name table in the first place :)

Am 10.06.2021 um 18:59 schrieb Julian Menzler ***@***.***>:

﻿

@julianmenzler commented on this pull request.

________________________________

In src/benchmark/join_order_benchmark.cpp<https://github.com/hyrise/hyrise/pull/2372#discussion_r649367014>:

> @@ -21,6 +21,88 @@
 using namespace opossum;               // NOLINT
 using namespace std::string_literals;  // NOLINT

+/**
+ * Each of the 20 JOB tables has one surrogate key. This function registers key constraints for all of them.


You are right, name is missing. Thanks for catching this!

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/hyrise/hyrise/pull/2372#discussion_r649367014>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAMUHTB7H2E347HVJXDAOD3TSDVQ3ANCNFSM46MYXXKQ>.

2021-06-10 17:25 UTC, julianmenzler commented
> Some queries lose performance. Is this due to the fact that the constraints enable JoinToSemiJoinRewrites (ColumnPruningRule) and these SemiJoins prevent some SemiJoinReductions?

Not sure if there is an easy explanation that fits all queries. But in 13a and 18a, some semi join placements get worse with constraints:

* In 13a, `Semi Join where kind_id = id)` gets placed above `Inner Join where id = movie_id`, making the latter more expensive (148ms vs. 4ms)

* In 18a, `Semi Join where info_type_id = id` gets placed above `Inner Join where movie_id = movie_id`, making the latter more expensive. (341ms vs. 204ms)

2021-06-11 06:51 UTC, julianmenzler commented
I updated the benchmark results. No real changes.

2021-06-11 08:04 UTC, Bouncner commented on src/benchmark/join_order_benchmark.cpp
> +  title_table->add_soft_key_constraint({{title_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});
If I look at these lines. Is there a reason not to loop over table_info_by_name and set the primary key on `id`?
Would have solved the `name` issue as well.

2021-06-11 08:18 UTC, Bensk1 commented
Currently, that would be fine. Originally, I also added foreign key constraints for some tables. As long as we don’t have them, there should be no difference.

Am 11.06.2021 um 10:04 schrieb Bouncner ***@***.***>:

﻿

@Bouncner commented on this pull request.

________________________________

In src/benchmark/join_order_benchmark.cpp<https://github.com/hyrise/hyrise/pull/2372#discussion_r649776411>:

> +  movie_link_table->add_soft_key_constraint(
+      {{movie_link_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});
+
+  const auto& name_table = table_info_by_name.at("name").table;
+  name_table->add_soft_key_constraint({{name_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});
+
+  const auto& person_info_table = table_info_by_name.at("person_info").table;
+  person_info_table->add_soft_key_constraint(
+      {{person_info_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});
+
+  const auto& role_type_table = table_info_by_name.at("role_type").table;
+  role_type_table->add_soft_key_constraint(
+      {{role_type_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});
+
+  const auto& title_table = table_info_by_name.at("title").table;
+  title_table->add_soft_key_constraint({{title_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});


If I look at these lines. Is there a reason not to loop over table_info_by_name and set the primary key on id?
Would have solved the name issue as well.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/hyrise/hyrise/pull/2372#pullrequestreview-681560180>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAMUHTBK5G5FI2BIPH6YRK3TSG7RBANCNFSM46MYXXKQ>.

2021-06-11 09:11 UTC, julianmenzler commented
> If I look at these lines. Is there a reason not to loop over table_info_by_name and set the primary key on id?
Would have solved the name issue as well.

To me, that sounds like a more hacky version, but it should work.

However, to stay consistent with `TPCHTableGenerator::_add_constraints`, `TPCCTableGenerator::_add_constraints` and `TPCDSTableGenerator::_add_constraints`, I would leave it as is. 
Also: With the current implementation, we can easily add other table constraints, such as FK constraints, without rewriting any code.

2021-06-11 09:49 UTC, Bouncner commented on src/benchmark/join_order_benchmark.cpp
> +  title_table->add_soft_key_constraint({{title_table->column_id_by_name("id")}, KeyConstraintType::PRIMARY_KEY});
Yeah, the FK issue you both mentioned makes sense to me.

2021-06-11 09:51 UTC, Bensk1 approved these changes

2021-06-11 09:51 UTC, merged