[DYOD]
hyrise/hyrise pull request #2393
Opened 2021-08-01 15:21 UTC by simonstadlinger

# [DYOD] DDL Project Pull Request

## What changes?

In this pull request we introduce support for DDL statements for the following topics: 
- create/drop index
- metatables for indexes
- tablekey and column constraints
- support for unsupported datatypes
- alter table drop column

In the next sections the changes and additions will be explained in detail.

This pull request should be reviewed and merged in conjunction with [this pull request](https://github.com/hyrise/sql-parser/pull/177) on the sql parser repository. 

### Create/drop index

For create and drop index we edited each part of the pipeline. Starting with the sql-parser we introduced rules for parsing create index and drop index statemens. We added translation methods in the sql-translator and introduced new lqp nodes for both operations. We added two new operatos which are created in newly added methods in the lqp-translator. The create index operator decides which index type to use; currently we support `GroupKeyIndex`, if a single column are given within the statement and `CompositeGroupKeyIndex`, if multiple columns are provided with the input.

The create index DDL statement for now supports:
- the `IF NOT EXISTS` flag
- multiple columns

The drop index DDL statement for now supports:
- the `IF EXISTS` flag

### Metatables for indexes

Hyrise has several meta tables (see meta_table_manager.hpp/cpp). For example, it is possible to get meta information about the stored tables with `SELECT * FROM meta_tables` or meta information about the columns with `SELECT * FROM meta_columns`. Similarly, you can now use `SELECT * FROM meta_indexes` to view meta information about the created index structures. In meta_indexes table one sees for each index the index type, the name, the table and the columns concerned.

### Tablekey and column constraints

For the table key constraints we edited the create table statement in all parts of the pipeline. Starting with an optional non terminal in the sql-parser, passing down information about the type of the constraint (PRIMARY KEY and UNIQUE), the name of the chosen table, and the specified columns, until we then, in the create table operator, use the already implemented add_soft_key_constraints method to add the constraints to the table.

For the column constraints, we modified the column_definition to now contain a variable of an enum class, storing information if and what constraint type is defined for the column. The constraints can again be set in the postgresql syntax in the console in the create table statement and then be parsed and stored in the dummy table that is send through the pipeline and used to create the actual table in the operator at the end. 

### Unsupported Datatypes

This PR makes it possible to declare columns of the Types date, time, character varying and decimal in the console. Unfortunately, these types are still not supported by hyrise, which is why we only map them to existing types in the sql translator and give a warning back to the user, so they know, what's happening and why. Internally, we map the decimal onto the float type and the others to the varchar type. 

Hyrise now supports the following datatypes:
* INT
* SMALLINT -> implicitly converted to INT
* INTEGER
* LONG
* FLOAT
* DECIMAL -> implicitly converted to FLOAT
* DOUBLE
* REAL
* VARCHAR
* CHARACTER VARYING -> implicitly converted to VARCHAR
* CHAR
* TEXT
* TIME -> implicitly converted to VARCHAR
* DATETIME -> implicitly converted to VARCHAR
* DATE -> implicitly converted to VARCHAR

### Alter Table drop column
Similar to the DROP and CREATE INDEX statement we also started to implement support for the ALTER statement. For now, only `ALTER TABLE mytable DROP COLUMN colname` is supported.

The ALTER TABLE DROP COLUMN DDL statement for now supports:
- the `IF EXISTS` flag

The ALTER TABLE DROP COLUMN DDL statement does not yet support:
- multiple columns

## What works
We executed the table benchmarks contained in https://github.com/cwida/public_bi_benchmark. All but 'IGlocations_2', 'HashTags_1','Euro2016', 'MulheresMil_1',
'RealEstate', 'Renabilidad_9',
'TableroSistemaPenal_6', 'TableroSistemaPenal_8',
'Telco_1', 'Uberlandia_1' and 'YaleLanguages_4' work.
This is mainly to the lacking support of bigint and timestamp.

2021-08-15 20:39 UTC, bengelhaupt reviewed
Great work on the DDL feature and the deep integration into the hyrise components!

We like the consistent coding of the statements and their operators as well as the thorough testing. You could have used some more comments on code and classes to make understanding it more easily. Unfortunately your CI pipeline did not pass for any compiler, so we could not assess your overall test coverage. Also your code is neither formatted nor linted, but the later CI steps will point that out too, as well as the overall code quality.

Overall a neat contribution!

/cc @vxrahn @Jasperhino

2021-08-15 20:39 UTC, bengelhaupt commented on src/lib/storage/table.cpp
> +    auto index = _indexes.at(index_id);
Unnecessary bounds checking.

2021-08-15 20:39 UTC, bengelhaupt commented on src/lib/storage/table.cpp
> +    }
We think you could also use the `erase-remove_if` idiom here.

2021-08-15 20:39 UTC, bengelhaupt commented on src/lib/storage/table.hpp
> +    const auto chunk_count = _chunks.size();
You could place this line above the for loop that uses it in line 211.

2021-08-15 20:39 UTC, bengelhaupt commented on src/lib/storage/table.hpp
> +      auto new_end = std::remove_if(
Isn't `new_end` the same as `index_stats`?

2021-08-15 20:39 UTC, bengelhaupt commented on src/lib/storage/table.hpp
> +      std::cout << "No index with name '" << name << "' exists.";
One of those two is redundant.

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/ddl/ddl_statement_test.cpp
> +  // EXPECT_THROW(second_sql_pipeline.get_result_table(), std::exception);
We do not see why this should not work. Maybe it fails in a later stage of this test?

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/logical_query_plan/create_table_node_test.cpp
> -
Redundant line removal.

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/operators/maintenance/create_index_test.cpp
> +  // TODO: is this test really doing what we think it does?
We are not sure what you are thinking it should do. Could you maybe specify it a bit more? :)

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/operators/maintenance/create_index_test.cpp
> +  // TODO implement test case
Missing test implementation.

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/storage/table_test.cpp
> +  EXPECT_EQ(t->column_count(), 1u);
Redundant line.

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/storage/table_test.cpp
> +  EXPECT_EQ(t->column_count(), 1u);
Redundant line.

2021-08-15 20:39 UTC, bengelhaupt commented on src/test/lib/operators/maintenance/drop_index_test.cpp
> +TEST_F(DropIndexTest, FailOnWrongIndexName) {
In its current implementation this test seems to test nothing.

2021-08-17 15:43 UTC, Jostafarr commented on src/lib/optimizer/strategy/column_pruning_rule.cpp
> +    case LQPNodeType::AlterDropColumn:
Interesting, how the cases we didn't touch already were not in the right order. @mweisgut Should we quickly fix this or is there a reasoning behind this?

2021-08-17 23:56 UTC, mweisgut requested changes
Thank you for your contribution. Some refactoring is required. In addition to the below comments, please make sure that the CI run can finish successfully.

2021-08-17 23:56 UTC, mweisgut commented on src/lib/storage/index/segment_index_type.cpp
> +  switch (type) {
To get the enum as string, you can use `magic_enum::enum_name`, which we also use in other code locations.

2021-08-17 23:56 UTC, mweisgut commented on src/lib/storage/table.cpp
> +void Table::delete_column(ColumnID column_id) {
The changes required to other classes for the realization of the ALTER TABLE DROP COLUM functionality should be as small as possible. Similar to `delete_segment(...)`, `delete_column(...)` should not implicitly remove additional data structures other than the actual column of the table. Removing the column and removing the indexes created for the column is the responsibility of the ALTER TABLE operator. Implementing `Table::remove_index` would complement `Table::create_index` and can then be called together with `delete_column` from the ALTER TABLE operator.

2021-08-17 23:56 UTC, mweisgut commented on src/lib/storage/table.hpp
> +  void delete_index_by_name(const std::string& name, const bool if_exists) {
This is another change caused by the ALTER TABLE operator implementation. Thus, it is only code used by the ALTER TABLE operator. We can avoid it by pushing more logic into the ALTER TABLE operator and adding the `Table::remove_index` function.

2021-08-17 23:56 UTC, mweisgut commented on src/lib/storage/table.hpp
> +  void delete_index_by_name(const std::string& name, const bool if_exists) {
I did not review this function any further since some refactoring will happen anyway.

2021-08-17 23:56 UTC, mweisgut commented on src/lib/utils/meta_tables/meta_indexes_table.cpp
> +      for (auto col_id : index.column_ids) {
```suggestion
      for (auto column_id : index.column_ids) {
```

2021-08-17 23:56 UTC, mweisgut commented on src/lib/utils/meta_tables/meta_indexes_table.cpp
> +        column_names += " " + table->column_name(col_id);
```suggestion
        column_names += " " + table->column_name(column_id);
```

2021-08-17 23:56 UTC, mweisgut commented on src/lib/utils/meta_tables/meta_indexes_table.cpp
> +      output_table->append({pmr_string{index.name}, static_cast<pmr_string>(segment_index_type_to_string(index.type)),
segment_index_type_to_string is not necessary here. magic_enum::enum_name can be used instead

2021-08-24 11:55 UTC, m0e33 commented on src/lib/logical_query_plan/drop_index_node.cpp
> +    : AbstractNonQueryNode(LQPNodeType::DropIndex), index_name(init_index_name), if_exists(init_if_exists), table_name(init_table_name) {}
@mweisgut We call `remove_index` on the `table`, thus we need the `table_name` to get the table from the `StorageManager`. Let me know if there is a nicer way to do it.

2021-08-24 12:29 UTC, m0e33 commented on src/lib/logical_query_plan/drop_index_node.cpp
> +    : AbstractNonQueryNode(LQPNodeType::DropIndex), index_name(init_index_name), if_exists(init_if_exists), table_name(init_table_name) {}
@mweisgut nevermind. I saw the issue, we are refactoring the DROP INDEX command.

2021-08-24 12:31 UTC, Jostafarr commented on src/lib/optimizer/strategy/column_pruning_rule.cpp
> +    case LQPNodeType::AlterDropColumn:
Whoops. I made a mistake here. Meant to ask that question for the optimizer.cpp. Should we ensure lexicographical order there?

2021-08-31 08:32 UTC, simonstadlinger commented
Good morning @mweisgut. We tried to fix the pipeline, but couldn't figure out every error. Could you please provide us with a hint on https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2393/36/pipeline/99 and https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2393/36/pipeline/101. Also we think that https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2393/36/pipeline/93 is not triggered through something we did, as well as https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2393/36/pipeline/94 and https://hyrise-ci.epic-hpi.de/blue/organizations/jenkins/hyrise%2Fhyrise/detail/PR-2393/36/pipeline/100  which seem related. Thank you in advance

2021-08-31 13:53 UTC, m0e33 commented
@mweisgut Refactoring of `AlterTable` Implementation is done. Please have a look at it and tell us if more implementation work is needed! 🎉

2021-12-03 08:56 UTC, closed without merging